### ISSUE TITLE
Implementation of custom svg icon from local file

### ISSUE THREAD

**Issue by excellencemichel** [octavenz/wagtailextraicons#10]
Hi ! Thank you for this plugin. May explain how can we add custom svg icon from our local file ? I attempt like you mentioned here but it not work. Thank you

**Comment by pjho** [comment]
I think that note in the readme is about contributing icons to this icon library. Both 1.x & 2.x of this library have a build task to add icons to the format needed, no way to add icons dynamically.

If you are using Wagtail 2.15 or greater adding icons is now really easy.
Here’s the doc: https://github.com/wagtail/wagtail/pull/6028/files . Not sure if live docs are updated with this yet. 

In a nutshell

*wagtail_hooks.py*

```
@hooks.register("register_icons")
def register_icons(icons):
    return icons + ['app/templates/icons/rocket.svg']
```

*app/templates/icons/rocket.svg*

```
<symbol id="icon-rocket" viewBox="0 0 16 16">
     <path d=""/>
</symbol>
```
