### ISSUE TITLE
heading-icon icon renders badly

### ISSUE THREAD

**Issue by richie-blake** [octavenz/wagtailextraicons#3]
<img width="259" alt="Screen Shot 2020-04-21 at 8 31 19 AM" src="https://user-images.githubusercontent.com/4099711/79797004-a2f70c80-83aa-11ea-943e-5449b312e3ac.png">

`    
class Meta:
    icon = 'extraicons--heading-icon'
`
Wagtail 2.7.2

@Sam-Costigan

**Comment by Sam-Costigan** [comment]
Thanks for reporting @richie-blake. These narrow icons have caused trouble before, they tend to render at full height and cut off the majority of the icon as you've shown. Looking into a fix now.

**Comment by Sam-Costigan** [comment]
I've pushed a fix so the heading icon will render correctly now:
<img width="263" alt="HeadingIcon" src="https://user-images.githubusercontent.com/2160222/79805976-75668f00-83bb-11ea-9388-6f90dea76952.png">

You'll need to update to wagtailextraicons 0.1.3. Let me know if there are still any issues, cheers!
