### ISSUE TITLE
Update to Wagtail register_icons hook

### ISSUE THREAD

**Issue by Sam-Costigan** [octavenz/wagtailextraicons#5]
Wagtail is phasing out font icons in favour of SVG: https://github.com/wagtail/wagtail/issues/6107

When more documentation becomes available for how this hook is intended to work, it would be good to update extraicons to make that available as well, while still maintaining the font icons for backwards compatibility.

**Comment by pjho** [comment]
Resolved in https://github.com/octavenz/wagtailextraicons/releases/tag/2.0.0
